// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	createProject: (name: string, width: number, height: number, fps: number) => typedError<Project, string>(__TAURI_INVOKE("create_project", { name, width, height, fps })),
	getProjects: () => typedError<Project[], string>(__TAURI_INVOKE("get_projects")),
	deleteProject: (id: string) => typedError<null, string>(__TAURI_INVOKE("delete_project", { id })),
	updateProjectName: (id: string, newName: string) => typedError<null, string>(__TAURI_INVOKE("update_project_name", { id, newName })),
};

/* Types */
export type Project = {
	id: string,
	name: string,
	viewport_width: number,
	viewport_height: number,
	framerate: number,
	created_at: string,
	updated_at: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

