// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core'

/** Commands */
export const commands = {
  createProject: (name: string, resolution: ResolutionPreset, fps: FpsPreset) =>
    typedError<Project_Serialize, string>(
      __TAURI_INVOKE('create_project', { name, resolution, fps }),
    ),
  getProjects: () =>
    typedError<Project_Serialize[], string>(__TAURI_INVOKE('get_projects')),
  getProject: (id: string) =>
    typedError<Project_Serialize, string>(
      __TAURI_INVOKE('get_project', { id }),
    ),
  deleteProject: (id: string) =>
    typedError<null, string>(__TAURI_INVOKE('delete_project', { id })),
  updateProjectName: (id: string, newName: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('update_project_name', { id, newName }),
    ),
  saveProjectTimeline: (id: string, timelineState: TimelineState_Deserialize) =>
    typedError<null, string>(
      __TAURI_INVOKE('save_project_timeline', { id, timelineState }),
    ),
  exportProject: (projectId: string, outputPath: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('export_project', { projectId, outputPath }),
    ),
  registerAsset: (
    projectId: string,
    filePath: string,
    durationMs: number | null,
  ) =>
    typedError<Asset, string>(
      __TAURI_INVOKE('register_asset', { projectId, filePath, durationMs }),
    ),
  getAssets: (projectId: string) =>
    typedError<Asset[], string>(__TAURI_INVOKE('get_assets', { projectId })),
  deleteAsset: (id: string) =>
    typedError<null, string>(__TAURI_INVOKE('delete_asset', { id })),
  renameAsset: (id: string, newName: string) =>
    typedError<null, string>(__TAURI_INVOKE('rename_asset', { id, newName })),
  readAssetBytes: (filePath: string) =>
    typedError<number[], string>(
      __TAURI_INVOKE('read_asset_bytes', { filePath }),
    ),
  extractAudio: (filePath: string) =>
    typedError<string, string>(__TAURI_INVOKE('extract_audio', { filePath })),
  readAssetRange: (filePath: string, offset: number | null, length: number) =>
    typedError<RangeResult, string>(
      __TAURI_INVOKE('read_asset_range', { filePath, offset, length }),
    ),
  readMoovBox: (filePath: string) =>
    typedError<RangeResult, string>(
      __TAURI_INVOKE('read_moov_box', { filePath }),
    ),
}

/* Types */
export type Asset = {
  id: string
  project_id: string
  name: string
  file_path: string
  media_type: string
  thumbnail_path: string | null
  duration_ms: number | null
  created_at: string
}

export type BackgroundConfig = {
  background_type: BackgroundType
  color_hex: string | null
}

export type BackgroundType = 'color' | 'blurred_input'

export type Clip = {
  id: string
  asset_id: string | null
  timeline_in: number
  timeline_out: number
  source_in: number
  source_out: number
  transform: Transform | null
  speed_factor?: number | null
  effects?: EffectConfig[]
}

export type EaseCurve = 'linear' | 'ease_in' | 'ease_out'

export type EffectConfig =
  | {
      type: 'zoom'
      params: {
        start_scale: number | null
        end_scale: number | null
        center_x: number | null
        center_y: number | null
        ease_curve: EaseCurve
      }
    }
  | {
      type: 'highlight'
      params: {
        shape: Shape
        color_hex: string
        stroke_width: number
        animation: string
      }
    }
  | {
      type: 'text_overlay'
      params: {
        text: string
        font_family: string
        font_size: number
        color_hex: string
      }
    }

export type FpsPreset = '15' | '30' | '60'

export type Project = Project_Serialize | Project_Deserialize

export type Project_Deserialize = {
  id: string
  name: string
  viewport_width: number
  viewport_height: number
  framerate: number
  timeline_state: TimelineState_Deserialize
  created_at: string
  updated_at: string
}

export type Project_Serialize = {
  id: string
  name: string
  viewport_width: number
  viewport_height: number
  framerate: number
  timeline_state: TimelineState_Serialize
  created_at: string
  updated_at: string
}

export type RangeResult = {
  bytes: number[]
  file_start: number | null
  total_length: number | null
}

export type ResolutionPreset = '1080p' | '4k' | 'vertical'

export type Shape = 'circle' | 'rectangle' | 'arrow' | 'highlighter'

export type TimelineState = TimelineState_Serialize | TimelineState_Deserialize

export type TimelineState_Deserialize = {
  playhead_position: number
  tracks: Track_Deserialize[]
  background?: BackgroundConfig | null
}

export type TimelineState_Serialize = {
  playhead_position: number
  tracks: Track_Serialize[]
  background: BackgroundConfig | null
}

export type Track = Track_Serialize | Track_Deserialize

export type TrackType = TrackType_Serialize | TrackType_Deserialize

export type TrackType_Deserialize = 'video' | 'Video' | 'audio' | 'Audio'

export type TrackType_Serialize = 'video' | 'audio'

export type Track_Deserialize = {
  id: string
  name: string
  track_type: TrackType_Deserialize
  clips: Clip[]
  transitions?: Transition[]
  is_muted?: boolean
  is_locked?: boolean
}

export type Track_Serialize = {
  id: string
  name: string
  track_type: TrackType_Serialize
  clips: Clip[]
  transitions: Transition[]
  is_muted: boolean
  is_locked: boolean
}

export type Transform = {
  x: number | null
  y: number | null
  scale: number | null
  z_index: number
}

export type Transition = {
  id: string
  from_clip_id: string
  to_clip_id: string
  transition_type: TransitionType
  duration_frames: number
  ease_curve: EaseCurve
}

export type TransitionType = 'fade' | 'slide' | 'wipe' | 'zoom'

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result }
  } catch (e) {
    if (e instanceof Error) throw e
    return { status: 'error', error: e as any }
  }
}
