// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from '@tauri-apps/api/core';

/** Commands */
export const commands = {
  createProject: (name: string, resolution: ResolutionPreset, fps: FpsPreset) =>
    typedError<Project, string>(
      __TAURI_INVOKE('create_project', { name, resolution, fps }),
    ),
  getProjects: () =>
    typedError<Project[], string>(__TAURI_INVOKE('get_projects')),
  getProject: (id: string) =>
    typedError<Project, string>(__TAURI_INVOKE('get_project', { id })),
  deleteProject: (id: string) =>
    typedError<null, string>(__TAURI_INVOKE('delete_project', { id })),
  updateProjectName: (id: string, newName: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('update_project_name', { id, newName }),
    ),
  saveProjectTimeline: (id: string, timelineState: TimelineState) =>
    typedError<TimelineState, string>(
      __TAURI_INVOKE('save_project_timeline', { id, timelineState }),
    ),
  getPresets: () => __TAURI_INVOKE<PresetsConfig>('get_presets'),
  getEditingRegistry: () =>
    __TAURI_INVOKE<EditingRegistry>('get_editing_registry'),
  getTimelineTranscript: (
    projectId: string,
    startFrame: number,
    endFrame: number,
  ) =>
    typedError<ComposedTranscript, string>(
      __TAURI_INVOKE('get_timeline_transcript', {
        projectId,
        startFrame,
        endFrame,
      }),
    ),
  registerAsset: (
    projectId: string,
    filePath: string,
    durationMs: number | null,
  ) =>
    typedError<Asset, string>(
      __TAURI_INVOKE('register_asset', { projectId, filePath, durationMs }),
    ),
  getAssets: (projectId: string) =>
    typedError<Asset[], string>(__TAURI_INVOKE('get_assets', { projectId })),
  deleteAsset: (id: string) =>
    typedError<null, string>(__TAURI_INVOKE('delete_asset', { id })),
  renameAsset: (id: string, newName: string) =>
    typedError<null, string>(__TAURI_INVOKE('rename_asset', { id, newName })),
  readAssetBytes: (filePath: string) =>
    typedError<number[], string>(
      __TAURI_INVOKE('read_asset_bytes', { filePath }),
    ),
  extractAudio: (filePath: string) =>
    typedError<string, string>(__TAURI_INVOKE('extract_audio', { filePath })),
  readAssetRange: (filePath: string, offset: number | null, length: number) =>
    typedError<RangeResult, string>(
      __TAURI_INVOKE('read_asset_range', { filePath, offset, length }),
    ),
  readMoovBox: (filePath: string) =>
    typedError<RangeResult, string>(
      __TAURI_INVOKE('read_moov_box', { filePath }),
    ),
  sliceAudioAsset: (
    filePath: string,
    startSec: number | null,
    durationSec: number | null,
  ) =>
    typedError<string, string>(
      __TAURI_INVOKE('slice_audio_asset', { filePath, startSec, durationSec }),
    ),
  runAgent: (
    projectId: string,
    sessionId: string,
    prompt: string,
    apiUrl: string | null,
    apiKey: string | null,
    model: string | null,
  ) =>
    typedError<string, string>(
      __TAURI_INVOKE('run_agent', {
        projectId,
        sessionId,
        prompt,
        apiUrl,
        apiKey,
        model,
      }),
    ),
  getMessages: (sessionId: string) =>
    typedError<Message[], string>(
      __TAURI_INVOKE('get_messages', { sessionId }),
    ),
  createMessage: (sessionId: string, role: MessageAuthor, content: string) =>
    typedError<Message, string>(
      __TAURI_INVOKE('create_message', { sessionId, role, content }),
    ),
  getSessions: (projectId: string) =>
    typedError<Session[], string>(
      __TAURI_INVOKE('get_sessions', { projectId }),
    ),
  createSession: (projectId: string) =>
    typedError<Session, string>(
      __TAURI_INVOKE('create_session', { projectId }),
    ),
  deleteSession: (sessionId: string) =>
    typedError<null, string>(__TAURI_INVOKE('delete_session', { sessionId })),
  inspectTimeline: (startFrame: number, endFrame: number, stepFrames: number) =>
    typedError<string, string>(
      __TAURI_INVOKE('inspect_timeline', { startFrame, endFrame, stepFrames }),
    ),
  submitTimelineSnapshots: (requestId: string, storyboardBase64: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('submit_timeline_snapshots', {
        requestId,
        storyboardBase64,
      }),
    ),
  saveTestStoryboard: (storyboardBase64: string) =>
    typedError<null, string>(
      __TAURI_INVOKE('save_test_storyboard', { storyboardBase64 }),
    ),
};

/* Types */
export type Adjustments = {
  brightness: number | null;
  contrast: number | null;
  saturation: number | null;
  vignette: number | null;
};

export type Animatable<T> = {
  has_keyframes: boolean;
  value: T;
  keyframes: Keyframe<T>[];
};

export type Asset = {
  id: string;
  project_id: string;
  name: string;
  file_path: string;
  media_type: string;
  thumbnail_path: string | null;
  duration_ms: number | null;
  created_at: string;
};

export type BackgroundConfig = {
  source: BackgroundSource;
  blur_value?: number;
};

export type BackgroundSource =
  | {
      type: 'solid';
      params: {
        color_hex: string;
      };
    }
  | {
      type: 'gradient';
      params: {
        gradient_type: string;
        colors: string[];
        angle_degrees: number | null;
      };
    };

export type Clip = {
  id: string;
  asset_id: string | null;
  timeline_in: number;
  timeline_out: number;
  source_in: number;
  source_out: number;
  transform: Transform | null;
  clip_transitions?: ClipTransitions | null;
  speed_factor?: number | null;
  effect_type?: string | null;
  effect_config?: any | null;
  adjustments?: Adjustments | null;
};

export type ClipTransitions = {
  in_transition: SingleClipTransition | null;
  out_transition: SingleClipTransition | null;
  loop_animation: SingleClipTransition | null;
};

export type ComposedTranscript = {
  text: string;
  words: ComposedWord[];
};

export type ComposedWord = {
  word: string;
  start_frame: number;
  end_frame: number;
  start_ms: number;
  end_ms: number;
};

export type EaseCurve =
  'linear' | 'ease_in' | 'ease_out' | 'ease_in_out' | 'spring' | 'bounce';

export type EditingRegistry = {
  tools: ToolDescriptor[];
  effects: EffectDescriptor[];
};

export type EffectDescriptor = {
  name: string;
  label: string;
  description: string;
  defaultDurationFrames: number;
  defaultConfigJson: string;
};

export type FpsConfig = {
  label: string;
  value: FpsPreset;
};

export type FpsPreset = '15' | '30' | '60';

export type Keyframe<T> = {
  frame: number;
  value: T;
  ease_curve: EaseCurve;
};

export type Message = {
  id: string;
  session_id: string;
  role: MessageAuthor;
  content: string;
  created_at: string;
  updated_at: string;
};

export type MessageAuthor = 'user' | 'agent' | 'tool';

export type PresetsConfig = {
  resolutions: ResolutionConfig[];
  fpsOptions: FpsConfig[];
};

export type Project = {
  id: string;
  name: string;
  viewport_width: number;
  viewport_height: number;
  framerate: number;
  timeline_state: TimelineState;
  created_at: string;
  updated_at: string;
};

export type RangeResult = {
  bytes: number[];
  file_start: number | null;
  total_length: number | null;
};

export type ResolutionConfig = {
  label: string;
  value: ResolutionPreset;
  width: number;
  height: number;
};

export type ResolutionPreset = '1080p' | '4k' | 'vertical';

export type Session = {
  id: string;
  project_id: string;
  created_at: string;
  updated_at: string;
};

export type SingleClipTransition = {
  transition_type: TransitionType;
  duration_frames: number;
  ease_curve: EaseCurve;
  config?: any | null;
};

export type TimelineState = {
  playhead_position: number;
  tracks: Track[];
  background?: BackgroundConfig | null;
};

export type ToolDescriptor = {
  name: string;
  label: string;
  description: string;
};

export type Track = {
  id: string;
  name: string;
  track_type: TrackType;
  clips: Clip[];
  transitions?: Transition[];
  is_muted?: boolean;
  is_locked?: boolean;
};

export type TrackType = 'video' | 'audio' | 'effects';

export type Transform = {
  x: Animatable<number | null>;
  y: Animatable<number | null>;
  scale: Animatable<number | null>;
  rotation: Animatable<number | null>;
  anchor_x: number | null;
  anchor_y: number | null;
  opacity: Animatable<number | null>;
  z_index: number;
};

export type Transition = {
  id: string;
  from_clip_id: string;
  to_clip_id: string;
  transition_type: TransitionType;
  duration_frames: number;
  ease_curve: EaseCurve;
  alignment: TransitionAlignment;
  config?: any | null;
};

export type TransitionAlignment = 'center' | 'start' | 'end';

export type TransitionType =
  'fade' | 'slide' | 'wipe' | 'zoom' | 'spin' | 'glitch';

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: 'ok'; data: T } | { status: 'error'; error: E }> {
  try {
    return { status: 'ok', data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: 'error', error: e as any };
  }
}
