[package]
name = "rush-asset-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
rush-db = { path = "../db" }

serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { workspace = true }
sqlite-vec = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
hound = { workspace = true }
whisper-rs = { workspace = true }
image = { workspace = true }
base64 = { workspace = true }
ndarray = { workspace = true }
ort = { workspace = true }
instant-clip-tokenizer = { workspace = true }
tauri = { workspace = true }
specta = { workspace = true }
